### ISSUE TITLE
how to prevent double starting?

### ISSUE THREAD

**Issue by bcherny** [dewe/nginx-server#1] opened 2016-03-07 18:43 UTC

**Comment by dewe** [comment] 2016-03-07 19:48
I haven't been experiencing that, afaik. Do you have a code sample to show what's going on?

**Comment by amcdnl** [comment] 2016-03-22 14:43
You could always cache the variable:

```
var serv;

function start() {
    if(!serv) serv = server.start();
 }

start();
```

**Comment by dewe** [comment] 2016-03-23 09:11
In my setup, I start/stop the server for each mocha test, like so:

```
beforeEach(function (done) {
    server.start(function () {
        my_upstream_server.listen(8000);
        my_upstream_server.register('GET');
    });
});

afterEach(function (done) {
    server.stop(function () {
        my_upstream_server.close(done);
    });
});
```

This works well in my setup. @bcherny: Do you think that's a way to go for you?

**Comment by dewe** [comment] 2016-03-24 21:57
I assume this issue is a duplicate of #2, or solved by suggestions above.

**Closed as completed by dewe** 2016-03-24 21:57 UTC
